public with sharing class APInventorCtrlWrapper {

        @AuraEnabled
        public string Id {get;set;}
    
    	@AuraEnabled
        public string PersonId {get;set;}
    
        @AuraEnabled
        public string Name {get;set;}
    
    	@AuraEnabled
        public string Email {get;set;}
    
    	@AuraEnabled
        public boolean IsAdmin {get;set;}
    
    	@AuraEnabled
        public string Rank {get;set;}
    
    	@AuraEnabled
        public string EmploymentCategory {get;set;}
    
    	@AuraEnabled
        public string Employmentstatus {get;set;}
    
    	@AuraEnabled
        public string Workday_cec_Id {get;set;}
    
    	@AuraEnabled
        public string UserStatus {get;set;}
    
    	@AuraEnabled
        public string CityName {get;set;}
    
    	@AuraEnabled
        public string CountryName {get;set;}
    
    
}