public class cmpAPiMngCreateWSWrraper {

    public data data;
	public class data {
		public String author {get;set;} 
		public String author_description {get;set;} 
		public String classw {get;set;} // in json: class
		public String class_description {get;set;} 
		public String content_type {get;set;} 
		public String create_date {get;set;} 
		public String create_profile_date {get;set;} 
		public String database {get;set;} 
		public String declared {get;set;} 
		public String default_security {get;set;} 
		public String description {get;set;} 
		public String document_number {get;set;} 
		public String effective_security {get;set;} 
		public String extension {get;set;} 
		public String has_subfolders {get;set;} 
		public String id {get;set;} 
		public String in_use {get;set;} 
		public String indexable {get;set;} 
		public String inherits_security {get;set;} 
		public String is_container_saved_search {get;set;} 
		public String is_content_saved_search {get;set;} 
		public String is_declared {get;set;} 
		public String is_external {get;set;} 
		public String is_external_as_normal {get;set;} 
		public String is_hidden {get;set;} 
		public String is_hipaa {get;set;} 
		public String is_in_use {get;set;} 
		public String iwl {get;set;} 
		public String last_user {get;set;} 
		public String last_user_description {get;set;} 
		public String location {get;set;} 
		public String name {get;set;} 
		public String operator {get;set;} 
		public String operator_description {get;set;} 
		public String owner {get;set;} 
		public String owner_description {get;set;} 
		public String retain_days {get;set;} 
		public String size {get;set;} 
		public String subtype {get;set;} 
		public String type {get;set;} 
		public String type_description {get;set;} 
		public String version {get;set;} 
		public String workspace_id {get;set;} 
		public String wstype {get;set;} 
    }
}