global with sharing class cmpAPiManageCreateFolderWrraper {
	
    global data data;
    global class data {
    	global String database;	//MB_SB
		global String default_security;	//public
		global String description;	//Sub Folder Created For Demo Purposes
		global String edit_date;	//2023-12-11T08:52:42Z
		global String effective_security;	//full_access
		global String folder_type;	//regular
		global String has_documents;
		global String has_subfolders;
		global String id;	//MB_SB!10
		global String is_container_saved_search;
		global String is_content_saved_search;
		global String is_external;
		global String is_external_as_normal;
		global String is_hidden;
		global String location;	//Demoville
		global String name;	//Demo Sub Folder
		global String owner;	//SYM_SVC
		global String owner_description;	//Symphony Service Account
		global String parent_id;	//MB_SB!1
		global String view_type;	//document
		global String wstype;	//folder
    }
        
}