@istest
public class cmpAPDocuSignResponseTest {
    @istest public static void meth(){
        cmpAPDocuSignResponse d= new cmpAPDocuSignResponse();
        d.errorMessage='test';
        d.envelopeId='test';
        d.uri='test';
        d.statusDateTime='test';
        d.errorCode='test';
        d.message='test';
        d.status='test';
        d.documentsUri='test';
        d.recipientsUri='test';
        d.attachmentsUri='test';
        d.envelopeUri='test';
        d.emailSubject='test';
        d.emailBlurb='test';
        d.customFieldsUri='test';
        d.autoNavigation='test';
        d.envelopeIdStamping='test';
        d.notificationUri='test';
        d.enableWetSign='test';
        d.allowMarkup='test';
        d.allowReassign='test';
        d.allowViewHistory='test';
        d.isSignatureProviderEnvelope='test';
        d.signerCanSignOnMobile='test';
        d.is21CFRPart11='test';
        d.purgeState='test';
        d.brandId='test';
        d.templatesUri='test';
        d.certificateUri='test';
        d.documentsCombinedUri='test';
        d.statusChangedDateTime='test';
        d.completedDateTime='test';
        d.sentDateTime='test';
        d.initialSentDateTime='test';
        d.deliveredDateTime='test';
        d.lastModifiedDateTime='test';
        d.createdDateTime='test';
        d.voidedDateTime='test';
        d.voidedReason='test';
        d.declinedDateTime='test';
        
        
    }

}