@isTest
public class cmpAPiMangUploadDocWrraperTest {

   
    @isTest
    static void testCmpAPiMangUploadDocWrraper() {
        
         cmpAPiMangUploadDocWrraper.data mockData = new cmpAPiMangUploadDocWrraper.data();
        mockData.database = 'MB_SB';
        mockData.document_number = '8';
        mockData.version = '1';
        mockData.name = 'Michael-Best_thumbnail_MB-LOGO-1024x306';
        mockData.author = 'SYM_SVC';
        mockData.operator = 'SYM_SVC';
        mockData.type = 'PNG';
        mockData.class_code = 'DOC';
        mockData.edit_date = '2023-12-13T15:37:40Z';
        mockData.system_edit_date = '2023-12-13T15:37:40Z';
        mockData.create_date = '2023-12-13T15:37:40Z';
        mockData.create_profile_date = '2023-12-13T15:37:40Z';
        mockData.retain_days = '365';
        mockData.size = '40732';
        mockData.is_declared = 'false';
        mockData.declared = 'true';
        mockData.location = 'DEFSERVER:\\FILES\\MB_SB\\SYM_SVC\\0\\1\\8.1';
        mockData.default_security = 'public';
        mockData.last_user = 'SYM_SVC';
        mockData.is_in_use = 'false';
        mockData.is_checked_out = 'false';
        mockData.access = 'full_access';
        mockData.author_description = 'Symphony Service Account';
        mockData.operator_description = 'Symphony Service Account';
        mockData.type_description = 'PNG';
        mockData.class_description = 'Document';
        mockData.last_user_description = 'Symphony Service Account';
        mockData.extension = 'png';
        mockData.content_type = 'D';
        mockData.edit_profile_date = '2023-12-13T15:37:40Z';
        mockData.is_external = 'false';
        mockData.is_external_as_normal = 'false';
        mockData.file_create_date = '2023-12-13T15:37:40Z';
        mockData.file_edit_date = '2023-12-13T15:37:40Z';
        mockData.is_hipaa = 'false';
        mockData.workspace_name = 'OCR Rendition Folder';
        mockData.id = 'MB_SB!8.1';
        mockData.in_use = 'false';
        mockData.indexable = 'true';
        mockData.wstype = 'document';
        mockData.iwl = 'iwl:dms=michaelbest-mobility.imanage.work&&lib=MB_SB&&num=8&&ver=1';
        mockData.workspace_id = 'MB_SB!1';
       
        
    }
}