global with sharing class cmpAPiMngDocMoveWrraper {

    global data data;
	global warnings[] warnings;
	global class data {
		global String access;	//full_access
		global String author;	//SYM_SVC
		global String author_description;	//Symphony Service Account
		global String class_code;	//DOC
		global String class_description;	//Document
		global String content_type;	//D
		global String create_date;	//2023-12-16T14:45:54Z
		global String create_profile_date;	//2023-12-16T14:45:54Z
		global String database;	//MB_SB
		global String declared;
		global String default_security;	//public
		global String document_number;	//23
		global String edit_date;	//2023-12-16T14:45:54Z
		global String edit_profile_date;	//2024-01-17T17:48:48Z
		global String extension;	//txt
		global String file_create_date;	//2023-12-16T14:45:54Z
		global String file_edit_date;	//2023-12-16T14:45:54Z
		global String id;	//MB_SB!23.1
		global String in_use;
		global String indexable;
		global String is_checked_out;
		global String is_declared;
		global String is_external;
		global String is_external_as_normal;
		global String is_hipaa;
		global String is_in_use;
		global String iwl;	//iwl:dms=michaelbest-mobility.imanage.work&&lib=MB_SB&&num=23&&ver=1
		global String last_user;	//SYM_SVC
		global String last_user_description;	//Symphony Service Account
		global String location;	//DEFSERVER:\FILES\MB_SB\SYM_SVC\0\1\23.1
		global String name;	//Updated Name Field
		global String operator;	//SYM_SVC
		global String operator_description;	//Symphony Service Account
		global String retain_days;	//365
		global String size;	//4
		global String system_edit_date;	//2023-12-16T14:45:54Z
		global String type;	//ANSI
		global String type_description;	//Windows Ansi Text
		global String version;	//1
		global String workspace_id;	//MB_SB!5
		global String workspace_name;	//iManage Cloud Monitor
		global String wstype;	//document
	}
	global class warnings {
	}
    
}