global with sharing class cmpAPiManageSearchUsersWrraper {
	global list<data> data{get;set;}
	
	global class data {
		global String id;	//SYM_SVC
		global String user_id_ex;	//sym_svc
		global String full_name;	//Symphony Service Account
		global String location;	//Waukesha
		global String allow_logon;
		global String email;	//SYM_SVC@MICHEALBEST.COM
		global String user_num;	//12
		global String doc_server;	//DEFSERVER07
		global String preferred_library;	//MB_SB
		global String user_nos;	//2
		global String pwd_changed_ts;	//2024-01-13T22:34:00Z
		global String password_never_expire;
		global String failed_logins;	//0
		global String force_password_change;
		global String is_external;
		global String exch_autodiscover;	//:ErrorNonExistentMailbox=8;01/13/2024 22:34:00
		global String edit_date;	//2023-11-10T20:41:31Z
		global String wstype;	//user
		global String user_id;	//SYM_SVC
		global String userid;	//SYM_SVC
		global String preferred_database;	//MB_SB
		global String login;
		global String pwd_never_expire;
		global String database;	//mb_sb
	}
    
}