global with sharing class cmpAPiMangUploadDocWrraper {
	global data data;
	global warnings[] warnings;
    
    
	global class data {
		global String database;	//MB_SB
		global String document_number;	//8
		global String version;	//1
		global String name;	//Michael-Best_thumbnail_MB-LOGO-1024x306
		global String author;	//SYM_SVC
		global String operator;	//SYM_SVC
		global String type;	//PNG
		global String class_code;	//DOC
		global String edit_date;	//2023-12-13T15:37:40Z
		global String system_edit_date;	//2023-12-13T15:37:40Z
		global String create_date;	//2023-12-13T15:37:40Z
		global String create_profile_date;	//2023-12-13T15:37:40Z
		global String retain_days;	//365
		global String size;	//40732
		global String is_declared;
		global String declared;
		global String location;	//DEFSERVER:\FILES\MB_SB\SYM_SVC\0\1\8.1
		global String default_security;	//public
		global String last_user;	//SYM_SVC
		global String is_in_use;
		global String is_checked_out;
		global String access;	//full_access
		global String author_description;	//Symphony Service Account
		global String operator_description;	//Symphony Service Account
		global String type_description;	//PNG
		global String class_description;	//Document
		global String last_user_description;	//Symphony Service Account
		global String extension;	//png
		global String content_type;	//D
		global String edit_profile_date;	//2023-12-13T15:37:40Z
		global String is_external;
		global String is_external_as_normal;
		global String file_create_date;	//2023-12-13T15:37:40Z
		global String file_edit_date;	//2023-12-13T15:37:40Z
		global String is_hipaa;
		global String workspace_name;	//OCR Rendition Folder
		global String id;	//MB_SB!8.1
		global String in_use;
		global String indexable;
		global String wstype;	//document
		global String iwl;	//iwl:dms=michaelbest-mobility.imanage.work&&lib=MB_SB&&num=8&&ver=1
		global String workspace_id;	//MB_SB!1
	}
    
	global class warnings {
	}
}