@isTest
public class cmpAPDocuSignSupplimentalAttachmentTest {
    @istest public static void testing()  {
        cmpAPDocuSignSupplimentalAttachment Doc=new cmpAPDocuSignSupplimentalAttachment();
        Doc.CVId='test';
        Doc.docTitle='test';
        Doc.isChecked=true;
        Doc.isFinalDoc='test';
        cmpAPDocuSignSupplimentalAttachment controller = new cmpAPDocuSignSupplimentalAttachment();

    
    }

}