@istest
public class cmpAPDocuSignRecipientTest {
    @istest public static void meth(){
        cmpAPDocuSignRecipient d=new cmpAPDocuSignRecipient();
        d.RecipientName='test';
        d.recipientEMailId='test';
        d.recipientRoleName='test';
        d.docketNo='test';
        d.applicationNo='test';
        d.applicationDate='test';
        d.inventionTitle='test';
        d.inventorNames='test';
        d.inventorNames1='test';
        d.signerName='test';
        d.InventorId='test';
       
    
	cmpAPDocuSignRecipient controller = new cmpAPDocuSignRecipient();
    cmpAPDocuSignRecipient controller1 = new cmpAPDocuSignRecipient('','','','','','','','','','','');
    
}
                                                           
}