@isTest
public class cmpDocuSignOtherTest {
    @istest public static void testing() {
        cmpDocuSignOther cmp = new cmpDocuSignOther();
        cmp.XPosition=2;
        cmp.YPosition=3;
        cmp.inventorNames='abc';
        cmp.DocumentId='test';
        cmp.PageNumber='test';
        cmpDocuSignOther controller = new cmpDocuSignOther();
        cmpDocuSignOther controller1 = new cmpDocuSignOther('','','',2,2);
       
        
    
    }

}