/**
* @File Name : TriggerConstants.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 31, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 31, 2024 |   | Initial Version
**/

public class TriggerConstants {
	public static Set<String> memTriggerBlocked = new Set<String>();
}